name: riverpod_navigator_example
description: riverpod_navigator_example
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.0
  tuple: ^2.0.0

dev_dependencies: 
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  functional_widget:
  json_serializable:
  test:

dependency_overrides:
  analyzer: ^2.1.0

flutter:
  uses-material-design: true